### ISSUE TITLE
Running on Mojave 

### ISSUE THREAD

**Issue by derd3000** [overseeing/AppleNotes2Joplin#2]
Hey!
Had to change some lines in code to make it work on Mojave and a german language setting in macOS:

Apple Script was not able to access the right menu bar items, so I used shortcuts:
````		
tell application "System Events"
	tell process "Notes"
		keystroke "a" using command down
		delay 0.2
		keystroke "c" using command down
	end tell
end tell
````

Also there was some Apple Notes rubbish in the final files so I had to add the following to the clean up session:

````				
set deleteHTMLline to {"<meta name=\"CocoaVersion\" content=\"1671.6\">"}
set myText to deleteLinesFromText(myText, deleteHTMLline) of me as text
````		

Thanks for your work!

**Comment by overseeing** [comment]
cool, I added your `1671.6` example to the script.

Didn't think about about the language menu issue! I originally used cmd-a and cmd-d but thought some may use something else as keyboard shortcuts and menus more reliable choice. Maybe they're not. If second person mentions this, I'll change it to keyboard shortcut method.
